"""Regenerate extensions/ollama-provider.ts from `ollama list`.

Run this whenever you pull or remove an Ollama model, so the pi provider
extension stays in sync with what's actually available locally.

Usage:
    uv run python scripts/regen_ollama_extension.py
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
EXT_PATH = REPO_ROOT / "extensions" / "ollama-provider.ts"


def list_ollama_models() -> list[str]:
    """Return the model tags reported by `ollama list` (first column, excluding header)."""
    try:
        result = subprocess.run(
            ["ollama", "list"],
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        sys.exit("error: `ollama` CLI not found in PATH")
    except subprocess.CalledProcessError as exc:
        sys.exit(f"error: `ollama list` failed: {exc.stderr.strip()}")

    lines = result.stdout.strip().splitlines()
    if len(lines) < 2:
        sys.exit("error: no models found. Pull one first, e.g. `ollama pull qwen3.6:35b`")

    tags = [line.split()[0] for line in lines[1:] if line.strip()]
    return sorted(set(tags))


def render_extension(tags: list[str]) -> str:
    """Render the TypeScript extension registering every Ollama tag as a pi model."""
    models = [
        {
            "id": tag,
            "name": f"{tag} (local)",
            "reasoning": True,
            "input": ["text"],
            "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
            "contextWindow": 131072,
            "maxTokens": 16384,
            "compat": {
                "supportsDeveloperRole": False,
                "thinkingFormat": "qwen-chat-template",
            },
        }
        for tag in tags
    ]
    models_literal = json.dumps(models, indent=2, ensure_ascii=False)

    return (
        "// Auto-generated by scripts/regen_ollama_extension.py — do not edit by hand.\n"
        "// Re-run that script after `ollama pull` or `ollama rm`.\n"
        "\n"
        "const OLLAMA_BASE_URL = process.env.OLLAMA_BASE_URL ?? "
        '"http://localhost:11434/v1";\n'
        "\n"
        "export default function (pi: any) {\n"
        '  pi.registerProvider("ollama", {\n'
        "    baseUrl: OLLAMA_BASE_URL,\n"
        '    apiKey: "ollama",\n'
        '    api: "openai-completions",\n'
        f"    models: {models_literal},\n"
        "  });\n"
        "}\n"
    )


def main() -> None:
    tags = list_ollama_models()
    EXT_PATH.write_text(render_extension(tags), encoding="utf-8")
    print(f"wrote {EXT_PATH.relative_to(REPO_ROOT)} with {len(tags)} model(s):")
    for tag in tags:
        print(f"  - {tag}")


if __name__ == "__main__":
    main()
