// Auto-generated by scripts/regen_ollama_extension.py — do not edit by hand.
// Re-run that script after `ollama pull` or `ollama rm`.

const OLLAMA_BASE_URL = process.env.OLLAMA_BASE_URL ?? "http://localhost:11434/v1";

export default function (pi: any) {
  pi.registerProvider("ollama", {
    baseUrl: OLLAMA_BASE_URL,
    apiKey: "ollama",
    api: "openai-completions",
    models: [
  {
    "id": "gemma4:26b",
    "name": "gemma4:26b (local)",
    "reasoning": true,
    "input": [
      "text"
    ],
    "cost": {
      "input": 0,
      "output": 0,
      "cacheRead": 0,
      "cacheWrite": 0
    },
    "contextWindow": 131072,
    "maxTokens": 16384,
    "compat": {
      "supportsDeveloperRole": false,
      "thinkingFormat": "qwen-chat-template"
    }
  },
  {
    "id": "qwen3.6:35b",
    "name": "qwen3.6:35b (local)",
    "reasoning": true,
    "input": [
      "text"
    ],
    "cost": {
      "input": 0,
      "output": 0,
      "cacheRead": 0,
      "cacheWrite": 0
    },
    "contextWindow": 131072,
    "maxTokens": 16384,
    "compat": {
      "supportsDeveloperRole": false,
      "thinkingFormat": "qwen-chat-template"
    }
  }
],
  });
}
